version: '3.5'

services:
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      # test: curl --fail http://127.0.0.1:2379/health || exit 1 
      test: etcdctl endpoint health
      interval: 5s
      timeout: 2s
      retries: 2
    networks:
      - ai
    # volumes:
    #    - ../../../volumes/etcd:/etcd
    # ports:
    #   - 2379:2379

  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0
    command: [ "milvus", "run", "standalone" ]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
      # minio.accessKeyID : minio
      # minio.secretAccessKey : minio123

      # volumes:
      #   - ../../../volumes/milvus:/var/lib/milvus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9091/healthz" ]
      start_period: 10s
      interval: 5s
      timeout: 2s
      retries: 4
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - ai

  ## this docker for dev purpose only
  attu:
    container_name: attu
    image: zilliz/attu:v2.3.10
    environment:
      MILVUS_URL: milvus:19530
    ports:
      - "7070:3000"
    networks:
      - ai

networks:
  ai:
    external: true
