
up:
	docker compose --file ./docker-compose.yaml --file ../object_storage/docker-compose.yaml up -d
down:
	docker compose --file ./docker-compose.yaml --file ../object_storage/docker-compose.yaml down
restart:
	docker compose --file ./docker-compose.yaml --file ../object_storage/docker-compose.yaml restart
ps:
	docker compose --file ./docker-compose.yaml --file ../object_storage/docker-compose.yaml ps